version: '2.0'
services:
  vscode:
    build: .
    environment:
      - DISPLAY=unix$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - password=password
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/docker/data:/home/newuser
      - /var/run/docker.sock:/var/run/docker.sock
